
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: Tetris
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: server
      src: ./
      replicas: 0
      ports:
       - name: http
         port: 80
      public: true